datasets:
- Beamline: MEG
  Data type - 1: PepperPot
  Data type - 2: 25 mm center
  LL: 0
  PILL position: Collimator
  QSK41cur: 18.1982
  QSK42cur: -40.7008
  QSK43cur: 34.8
  SML41cur: -10
  Simulation n.: 0
  fileName: Data_2022_MEG/Collimator/pepperpot001.txt
  poszPILL: 2323
- Beamline: MEG
  Data type - 1: PepperPot
  Data type - 2: 25 mm staggered
  LL: 0
  PILL position: Collimator
  QSK41cur: 18.1982
  QSK42cur: -40.7008
  QSK43cur: 34.8
  SML41cur: -10
  Simulation n.: 0
  fileName: Data_2022_MEG/Collimator/pepperpot002.txt
- Beamline: MEG
  Data type - 1: PepperPot
  Data type - 2: blind
  LL: 0
  PILL position: Collimator
  QSK41cur: 18.1982
  QSK42cur: -40.7008
  QSK43cur: 34.8
  SML41cur: -10
  Simulation n.: 0
  fileName: Data_2022_MEG/Collimator/pepperpot003.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 22.14
  QSK42cur: -41.64
  QSK43cur: 31.0
  SML41cur: 0
  Simulation n.: 1
  fileName: Data_2022_MEG/Collimator/tomo00.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 20.39
  QSK42cur: -41.37
  QSK43cur: 33.07
  SML41cur: 0
  Simulation n.: 2
  fileName: Data_2022_MEG/Collimator/tomo01.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 21.41
  QSK42cur: -41.56
  QSK43cur: 31.96
  SML41cur: 0
  Simulation n.: 3
  fileName: Data_2022_MEG/Collimator/tomo02.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 21.04
  QSK42cur: -41.51
  QSK43cur: 32.39
  SML41cur: 0
  Simulation n.: 4
  fileName: Data_2022_MEG/Collimator/tomo03.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 22.7
  QSK42cur: -41.66
  QSK43cur: 30.13
  SML41cur: 0
  Simulation n.: 5
  fileName: Data_2022_MEG/Collimator/tomo04.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 21.75
  QSK42cur: -41.62
  QSK43cur: 31.53
  SML41cur: 0
  Simulation n.: 6
  fileName: Data_2022_MEG/Collimator/tomo05.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 14.64
  QSK42cur: -39.13
  QSK43cur: 36.47
  SML41cur: 0
  Simulation n.: 7
  fileName: Data_2022_MEG/Collimator/tomo06.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 16.06
  QSK42cur: -39.81
  QSK43cur: 35.93
  SML41cur: 0
  Simulation n.: 8
  fileName: Data_2022_MEG/Collimator/tomo07.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 16.75
  QSK42cur: -40.12
  QSK43cur: 35.62
  SML41cur: 0
  Simulation n.: 9
  fileName: Data_2022_MEG/Collimator/tomo08.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 15.82
  QSK42cur: -39.71
  QSK43cur: 36.05
  SML41cur: 0
  Simulation n.: 10
  fileName: Data_2022_MEG/Collimator/tomo09.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 15.1
  QSK42cur: -39.37
  QSK43cur: 36.35
  SML41cur: 0
  Simulation n.: 11
  fileName: Data_2022_MEG/Collimator/tomo10.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 14.31
  QSK42cur: -38.97
  QSK43cur: 36.65
  SML41cur: 0
  Simulation n.: 12
  fileName: Data_2022_MEG/Collimator/tomo11.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 24.1
  QSK42cur: -18.97
  QSK43cur: -11.78
  SML41cur: 0
  Simulation n.: 13
  fileName: Data_2022_MEG/Collimator/tomoN00.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 25.39
  QSK42cur: -24.06
  QSK43cur: -8.18
  SML41cur: 0
  Simulation n.: 14
  fileName: Data_2022_MEG/Collimator/tomoN01.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 25.8
  QSK42cur: -25.8
  QSK43cur: -7.01
  SML41cur: 0
  Simulation n.: 15
  fileName: Data_2022_MEG/Collimator/tomoN02.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 26.15
  QSK42cur: -27.26
  QSK43cur: -6.05
  SML41cur: 0
  Simulation n.: 16
  fileName: Data_2022_MEG/Collimator/tomoN03.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 26.68
  QSK42cur: -29.63
  QSK43cur: -4.53
  SML41cur: 0
  Simulation n.: 17
  fileName: Data_2022_MEG/Collimator/tomoN04.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: vertical
  LL: 1
  PILL position: Collimator
  QSK41cur: 27.34
  QSK42cur: -32.62
  QSK43cur: -2.67
  SML41cur: 0
  Simulation n.: 18
  fileName: Data_2022_MEG/Collimator/tomoN05.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: -13.32
  QSK42cur: -9.45
  QSK43cur: 29.57
  SML41cur: 0
  Simulation n.: 19
  fileName: Data_2022_MEG/Collimator/tomoN06.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 7.55
  QSK42cur: -34.27
  QSK43cur: 35.81
  SML41cur: 0
  Simulation n.: 20
  fileName: Data_2022_MEG/Collimator/tomoN07.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 14.25
  QSK42cur: -38.93
  QSK43cur: 36.62
  SML41cur: 0
  Simulation n.: 21
  fileName: Data_2022_MEG/Collimator/tomoN08.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 15.31
  QSK42cur: -40.13
  QSK43cur: 38.95
  SML41cur: 0
  Simulation n.: 22
  fileName: Data_2022_MEG/Collimator/tomoN09.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: -6.08
  QSK42cur: -21.91
  QSK43cur: 38.52
  SML41cur: 0
  Simulation n.: 23
  fileName: Data_2022_MEG/Collimator/tomoN10.txt
- Beamline: MEG
  Data type - 1: Tomography
  Data type - 2: horizontal
  LL: 1
  PILL position: Collimator
  QSK41cur: 7.73
  QSK42cur: -36.29
  QSK43cur: 44.03
  SML41cur: 0
  Simulation n.: 24
  fileName: Data_2022_MEG/Collimator/tomoN11.txt
- Beamline: MEGCOBRA
  Data type - 1: RasterScan
  Data type - 2: horizontal
  LL: 0
  PILL position: COBRA
  QSK41cur: 18.5
  QSK42cur: -44.1
  QSK43cur: 43
  SMH41: 200
  SML41cur: -25
  SMV41: 72.5
  Simulation n.: 25
  fileName: Data_2022_MEG/COBRA/rasterscan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 30
  SML41cur: -10
  Simulation n.: 26
  fileName: Data_2022_Mu3e/Collimator/QSK43_30A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 31
  SML41cur: -10
  Simulation n.: 27
  fileName: Data_2022_Mu3e/Collimator/QSK43_31A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 32
  SML41cur: -10
  Simulation n.: 28
  fileName: Data_2022_Mu3e/Collimator/QSK43_32A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 33
  SML41cur: -10
  Simulation n.: 29
  fileName: Data_2022_Mu3e/Collimator/QSK43_33A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 34
  SML41cur: -10
  Simulation n.: 30
  fileName: Data_2022_Mu3e/Collimator/QSK43_34A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 34.8
  SML41cur: -10
  Simulation n.: 31
  fileName: Data_2022_Mu3e/Collimator/QSK43_348A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 35
  SML41cur: -10
  Simulation n.: 32
  fileName: Data_2022_Mu3e/Collimator/QSK43_35A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 36
  SML41cur: -10
  Simulation n.: 33
  fileName: Data_2022_Mu3e/Collimator/QSK43_36A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 37
  SML41cur: -10
  Simulation n.: 34
  fileName: Data_2022_Mu3e/Collimator/QSK43_37A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 38
  SML41cur: -10
  Simulation n.: 35
  fileName: Data_2022_Mu3e/Collimator/QSK43_38A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 39
  SML41cur: -10
  Simulation n.: 36
  fileName: Data_2022_Mu3e/Collimator/QSK43_39A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 40
  SML41cur: -10
  Simulation n.: 37
  fileName: Data_2022_Mu3e/Collimator/QSK43_40A_180kV_fastScan.txt
- Beamline: Mu3e
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: Collimator
  QSK41cur: 18.2
  QSK42cur: -40.7
  QSK43cur: 41
  SML41cur: -10
  Simulation n.: 38
  fileName: Data_2022_Mu3e/Collimator/QSK43_41A_180kV_fastScan.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 250
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 39
  fileName: Data_2022_Mu3e/QSM41/QSM41_250.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 240
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 40
  fileName: Data_2022_Mu3e/QSM41/QSM41_240.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 230
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 41
  fileName: Data_2022_Mu3e/QSM41/QSM41_230.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 220
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 42
  fileName: Data_2022_Mu3e/QSM41/QSM41_220.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 200
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 43
  fileName: Data_2022_Mu3e/QSM41/QSM41_200.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 190
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 44
  fileName: Data_2022_Mu3e/QSM41/QSM41_190.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 180
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 45
  fileName: Data_2022_Mu3e/QSM41/QSM41_180.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 150
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 46
  fileName: Data_2022_Mu3e/QSM41/QSM41_150.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 120
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 47
  fileName: Data_2022_Mu3e/QSM41/QSM41_120.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 60
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 48
  fileName: Data_2022_Mu3e/QSM41/QSM41_060.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 30
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 49
  fileName: Data_2022_Mu3e/QSM41/QSM41_030.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: 0
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 50
  fileName: Data_2022_Mu3e/QSM41/QSM41_000.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: -30
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 51
  fileName: Data_2022_Mu3e/QSM41/QSM41_-030.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: -90
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 52
  fileName: Data_2022_Mu3e/QSM41/QSM41_-090.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: -150
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 53
  fileName: Data_2022_Mu3e/QSM41/QSM41_-150.txt
- ASK41cur: -92
  ASL41cur: -74.7
  Beamline: Mu3eQSM
  Data type - 1: QuadScan
  Data type - 2: ''
  LL: 1
  PILL position: QSM41
  QSK41cur: 11
  QSK42cur: -35.5
  QSK43cur: 30
  QSM41cur: -250
  QSO41cur: 56
  QSO42cur: -23
  SML41cur: 0
  Simulation n.: 54
  fileName: Data_2022_Mu3e/QSM41/QSM41_-250.txt
pepperpot:
- A: 0.305025
  l1: 21.3552
  l2: 0.000606746
  mu: -7.61315
  s1: 47.6013
  s2: 59.2614
  x: -37.5
- A: 1.25203
  l1: -13.8584
  l2: 0.000208319
  mu: 17.5435
  s1: 71.0772
  s2: 79.4099
  x: -25
- A: 2.21984
  l1: -10.0195
  l2: -1.43565
  mu: -3.37802
  s1: 74.0407
  s2: 83.4557
  x: -12.5
- A: 2.27543
  l1: 11.4565
  l2: -9.79076
  mu: -0.708914
  s1: 69.8991
  s2: 84.0871
  x: 0
- A: 1.71837
  l1: 4.24545
  l2: -8.52998
  mu: -11.2332
  s1: 77.5932
  s2: 81.6965
  x: 12.5
- A: 0.842063
  l1: -0.0166016
  l2: 17.7025
  mu: -5.04023
  s1: 87.4775
  s2: 76.8209
  x: 25
- A: 0.276368
  l1: 0.0178001
  l2: 8.48725
  mu: -36.5828
  s1: 56.2147
  s2: 80.8401
  x: 37.5
- A: 0.167254
  l1: -11.1519
  l2: -0.00220219
  mu: -45.9839
  s1: 53.9635
  s2: 67.1783
  y: -37.5
- A: 0.603629
  l1: 25.8495
  l2: -0.521432
  mu: -29.0109
  s1: 47.6519
  s2: 68.406
  y: -25
- A: 1.28803
  l1: -1.91722
  l2: -2.07289
  mu: -10.2674
  s1: 70.5986
  s2: 62.9971
  y: -12.5
- A: 2.28991
  l1: -7.02367
  l2: -11.5799
  mu: -0.215761
  s1: 65.043
  s2: 55.8103
  y: 0
- A: 1.64781
  l1: -2.36211
  l2: -3.55077
  mu: -2.13186
  s1: 64.3065
  s2: 69.9394
  y: 12.5
- A: 1.22517
  l1: 0.265646
  l2: -14.4382
  mu: -1.38467
  s1: 64.7991
  s2: 59.8198
  y: 25
- A: 0.427013
  l1: -10.2908
  l2: 2.38926
  mu: 6.17808
  s1: 47.7518
  s2: 71.9936
  y: 37.5
simulations:
  DSbeam: PepperPotPhaseSpace.root
  DSbeamName: beam
  Invert:
    Beamline: MEGconfiguration.g4bl
    QSK41cur: -18.1982
    QSK42cur: 40.7008
    QSK43cur: -34.8
    SML41cur: 10
    beamPositionZ: 2323
    poszPILL: 0
  MEG: MEGconfiguration.g4bl
  MEGCOBRA: MEGCOBRAconfiguration.g4bl
  Mu3e: Mu3econfiguration.g4bl
  Mu3eQSM: Mu3eQSMconfiguration.g4bl
  USbeam: USbeam.root
  USbeamName: beam
